name: CI-CD-DataBase
env:
  DB_DATABASE: coursework
  DB_USER: root
  DB_PASSWORD: root

on: 
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: MySQL Version
      run: mysql --version

    - name: Import DB
      run: |
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        echo '---------------------------------'
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < coursework.sql
        mysql -e 'use ${{ env.DB_DATABASE }}; show tables;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        echo '---------------------------------'

    - uses: liquibase-github-actions/status@v4.24.0
      with:
            changelogFile: "coursework.sql"
            url: "jdbc:mysql://127.0.0.1:3306/coursework"
            headless: true
            username: ${{ env.DB_USER }}
            password: ${{ env.DB_PASSWORD }}
            logLevel: INFO    
    
    - name: Print Happy Message for CI finish
      run : echo "CI Pipeline part Finished successfully!"
