name: Liquibase Migrations

on:
  push:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mysql:
        
        # Docker Hub image
        image: mysql:latest
        
        # Provide the password for postgres
        env:
          MYSQL_ROOT_PASSWORD: '12345qwe'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
       
    
    steps:
         
        - uses: actions/checkout@v3
        - uses: liquibase-github-actions/status@v4.24.0
          with:
            changelogFile: "src/main/resources/changelogs/coursework.sql"
            url: "jdbc:mysql://mysql:5432/test2"
            headless: true
            username: 'root'
            password: '12345qwe'
            logLevel: INFO
        - uses: liquibase-github-actions/update@v4.24.0
          with:
                  
            classpath: "src/main/resources/changelogs"
            changeLogFile: "coursework.sql"
            username: 'root'
            password: '12345qwe'
            url: "jdbc:mysql://mysql:5432/coursework"
            logLevel: INFO
            #logFile: "src/main/resources/changelogs/liquibase.txt"
            #databaseChangeLogTableName:  "src/main/resources/changelogs/database_changelog.txt"
            #databaseChangeLogLockTableName:  "src/main/resources/changelogs/database_changelog_lockt.txt"
        
        #- uses: liquibase-github-actions/generate-changelog@v4.24.0
          #with:
            #username: ${{ secrets.USERNAME }}
            #password: ${{ secrets.PASSWORD }}
            #url: "jdbc:postgresql://postgres:5432/test"
            #headless: true          
            #logLevel: INFO

       
        
