name: CI-CD-DataBase
env:
  TEST : "test"

on: 
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: windows #ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3

    - name: MySQL Install
      uses: shogo82148/actions-setup-mysql@v1.3.0
      with:
        mysql-version: '8.0'
        auto-start: true
    - name: create test database
      run: mysql -h 127.0.0.1 -P 3306 -u root -e 'CREATE DATABASE test_db;'
    - name: show databases
      run: mysql -h 127.0.0.1 -P 3306 -u root -e 'SHOW DATABASES;'
    - name: setup user
      run: mysql -h 127.0.0.1 -P 3306 -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
    - name: flush privileges
      run: mysql -h 127.0.0.1 -P 3306 -u root -e 'FLUSH PRIVILEGES' -ppassword

    - name: MySQL Version
      run: mysql --version
    
    - name: Print Happy Message for CI finish
      run : echo "CI Pipeline part Finished successfully!"
