name: CI-CD-DataBase
env:
  TEST : "test"

on: 
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3

    #- name: MySQL Install
      #uses: mirromutth/mysql-action@v1.1
      #with:
       #   host port: 3306 # Optional, default value is 3800. The port of host
       #   container port: 3306 # Optional, default value is 3307. The port of container
       #   character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
       #   collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
       #   mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
       #   mysql database: 'coursework' # Optional, default value is "test". The specified database which will be create
       #   mysql root password: '12345qwer' # Required if "mysql user" is empty, default is empty. The root superuser password

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        #mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: MySQL Version
      run: mysql --version

    #- name: Import DB
     # run: |
     #   service mysql start
     #   mysql --user=root --password=12345qwer
     #   #CREATE DATABASE coursework;
     #   use coursework
     #   source coursework.sql
    
    - name: Print Happy Message for CI finish
      run : echo "CI Pipeline part Finished successfully!"
