name: CI-CD-DataBase
env:
  DB_DATABASE: coursework
  DB_USER: root
  DB_PASSWORD: root

on: 
  push:
    branches: 
      - main
      
permissions:
  contents: write

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Install Liquibase
      run: |
        wget -O- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > liquibase-keyring.gpg && \
        cat liquibase-keyring.gpg | sudo tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null && \
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | sudo tee /etc/apt/sources.list.d/liquibase.list
        sudo apt-get update
        sudo apt-get install liquibase

    - name: Import DB
      run: |
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        echo '---------------------------------'
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < coursework.sql
        mysql -e 'use ${{ env.DB_DATABASE }}; show tables;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        echo '---------------------------------' 

    - name: Install mysql driver
      run: |
        sudo apt update
        sudo apt install libmariadb-java
        cp /usr/share/java/mariadb-java-client.jar .. 
    
    - name: start Liquibase
      run: |
        liquibase init project \
        --changelog-file=mysql.changelog.sql \
        --format=sql \
        --url=jdbc:mysql://localhost:3306/coursework \
        --username=${{ env.DB_USER }} \
        --password=${{ env.DB_PASSWORD }}
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.3
      with:
          add: 'mysql.changelog.sql' 
     
    - name: Complete finish
      run : echo "Complete successfully!"
