name: Tests

on: [ push ]

jobs:
  tests:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        wp-versions: [ 5.6 ]
        php-versions: [ 7.4 ]

    name: WP ${{ matrix.wp-versions }} on PHP ${{ matrix.php-versions }}

    env:
      php-ini-values: post_max_size=256M
      wp-bp-directory: src/wp-content/plugins/buddypress
      DB_DATABASE: courseworkDB
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: localhost

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE courseworkDB;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: pecl
          php-version: ${{ matrix.php-versions }}
          ini-values: ${{ env.php-ini-values }}
        env:
          update: true

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0

      - name: Install phpunit 5.x on PHP 5.6
        if: ${{ matrix.php-versions == '5.6' }}
        run: |
          composer global require --dev phpunit/phpunit ^5 -q --prefer-dist --no-progress --ansi --no-interaction --no-suggest
          phpunit --version
      - name: Install phpunit 6.x on PHP 7.4
        if: ${{ matrix.php-versions == '7.4' }}
        run: |
          composer global require --dev phpunit/phpunit ^6 -q --prefer-dist --no-progress --ansi --no-interaction --no-suggest
          phpunit --version
      - name: Set up tests config
        run: |
          cp New_table_db.php index.php
          sed -i "s/youremptytestdbnamehere/${{ env.DB_DATABASE }}/" index.php
          sed -i "s/yourusernamehere/${{ env.DB_USER }}/" index.php
          sed -i "s/yourpasswordhere/${{ env.DB_PASSWORD }}/" index.php
          sed -i "s/localhost/${{ env.DB_HOST }}:${{ job.services.mysql.ports['3306'] }}/" index.php
      - name: Upload build artifact (TEMP)
        uses: actions/upload-artifact@v2
        with:
          name: wp-${{ matrix.wp-versions }}-php-${{ matrix.php-versions }}
          path: index.php
