name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows 2022
    env:
      php-ini-values: post_max_size=256M
      DB_DATABASE: courseworkDB
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: localhost
    steps:
    - uses: actions/checkout@v3
    - uses: mirromutth/mysql-action@v1.1

    - name: Create MySQL Database
      run: |
        sudo apt-get update && sudo apt-get install -y mysql-client
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
