on:
  - pull_request
  - push

name: build

jobs:
  tests:
    runs-on: windows
    name: example
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: coursework
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      
      - name: Create MySQL Database
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port $ -uroot -proot -e 'CREATE SCHEMA `coursework` CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL ON `coursework`.* TO root@localhost IDENTIFIED BY "root"; FLUSH PRIVILEGES;'
